import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "20mb" }));

// Helper to instantiate GoogleGenAI safely
function getGenAI() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return null;
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
}

// API Routes
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

// 1. AI General Assistant & Concept Explainer
app.post("/api/gemini/assistant", async (req, res) => {
  try {
    const { prompt, mode, history } = req.body;
    const ai = getGenAI();

    if (!ai) {
      return res.status(500).json({
        success: false,
        error: "GEMINI_API_KEY environment variable is missing on the server. Please configure GEMINI_API_KEY in your environment or Secrets panel.",
      });
    }

    if (!prompt || typeof prompt !== "string" || !prompt.trim()) {
      return res.status(400).json({
        success: false,
        error: "Message prompt cannot be empty.",
      });
    }

    let systemInstruction = "You are CampusPilot AI, an elite university study assistant and academic tutor. Provide clear, well-formatted, thorough answers with Markdown, step-by-step guidance, equations, code blocks where applicable, and academic rigor.";
    if (mode === 'math') systemInstruction += " Focus on step-by-step mathematical derivations, proofs, formulas, and problem solutions.";
    if (mode === 'code') systemInstruction += " Provide clean, well-commented code in TypeScript/Python/C++ with complexity analysis and edge cases.";
    if (mode === 'grammar') systemInstruction += " Provide precise grammar corrections, tone improvements, and academic style advice.";
    if (mode === 'viva') systemInstruction += " Act as a university professor conducting a viva voce exam. Ask probing questions, evaluate answers, and offer constructive academic feedback.";

    // Format chat history for Gemini contents if history array is provided
    let contents: any = prompt.trim();
    if (history && Array.isArray(history) && history.length > 0) {
      const formattedHistory = history
        .filter((msg: any) => msg && msg.content && !msg.isError)
        .slice(-12) // Keep last 12 messages for conversation context
        .map((msg: any) => ({
          role: msg.role === 'assistant' ? 'model' : 'user',
          parts: [{ text: msg.content }],
        }));

      formattedHistory.push({
        role: 'user',
        parts: [{ text: prompt.trim() }],
      });
      contents = formattedHistory;
    }

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents,
      config: {
        systemInstruction,
        temperature: 0.7,
      },
    });

    const replyText = response.text || "No response generated by Gemini API.";

    return res.json({
      success: true,
      text: replyText,
      reply: replyText,
    });
  } catch (error: any) {
    console.error("Error in /api/gemini/assistant:", error);
    return res.status(500).json({
      success: false,
      error: error.message || "Failed to generate AI response from Gemini API.",
    });
  }
});

// 2. AI Document & Notes Assistant (Summarize, Flashcards, MCQs, Viva)
app.post("/api/gemini/document-assistant", async (req, res) => {
  try {
    const { content, action, targetLanguage } = req.body;
    const ai = getGenAI();

    if (!ai) {
      return res.status(500).json({
        success: false,
        error: "GEMINI_API_KEY environment variable is missing on the server.",
      });
    }

    if (!content || !content.trim()) {
      return res.status(400).json({ success: false, error: "Content cannot be empty." });
    }

    let prompt = "";
    if (action === 'summarize') prompt = `Summarize the following study notes clearly with bullet points, key takeaways, and formulas:\n\n${content}`;
    else if (action === 'flashcards') prompt = `Generate 5 high-yield flashcards from this content in JSON format array [{ "front": "question", "back": "answer" }]:\n\n${content}`;
    else if (action === 'mcqs') prompt = `Generate 4 multiple-choice exam questions with answers and explanations from this content in Markdown format:\n\n${content}`;
    else if (action === 'viva') prompt = `Generate 5 top Viva Voce / oral exam questions with concise model answers for:\n\n${content}`;
    else if (action === 'translate') prompt = `Translate the following study material accurately into ${targetLanguage || 'Spanish'}:\n\n${content}`;
    else prompt = `Analyze and extract important key terms and formulas from:\n\n${content}`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });

    return res.json({
      success: true,
      text: response.text || "",
    });
  } catch (error: any) {
    console.error("Error in /api/gemini/document-assistant:", error);
    return res.status(500).json({ success: false, error: error.message || "Failed document processing" });
  }
});

// 3. AI Study Planner Generator
app.post("/api/gemini/planner", async (req, res) => {
  try {
    const { subjects, examDates, dailyHours } = req.body;
    const ai = getGenAI();

    if (!ai) {
      return res.status(500).json({
        success: false,
        error: "GEMINI_API_KEY environment variable is missing on the server.",
      });
    }

    const prompt = `Act as an expert academic counselor. Create an optimal study schedule for a university student.
Subjects: ${JSON.stringify(subjects)}
Exam Dates: ${JSON.stringify(examDates)}
Daily Available Study Hours: ${dailyHours} hours

Return JSON with structure:
{
  "dailyPlan": [{ "time": "string", "subject": "string", "focus": "string", "priority": "High/Medium/Low" }],
  "weeklyStrategy": "string",
  "revisionSchedule": [{ "day": "string", "task": "string" }]
}`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      },
    });

    let planData = {};
    try {
      planData = JSON.parse(response.text || "{}");
    } catch {
      planData = { rawText: response.text };
    }

    return res.json({ success: true, plan: planData });
  } catch (error: any) {
    console.error("Error in /api/gemini/planner:", error);
    return res.status(500).json({ success: false, error: error.message || "Failed to generate study plan" });
  }
});

// 4. AI Assignment Assistant
app.post("/api/gemini/assignment", async (req, res) => {
  try {
    const { title, description, dueDate, subject } = req.body;
    const ai = getGenAI();

    if (!ai) {
      return res.status(500).json({
        success: false,
        error: "GEMINI_API_KEY environment variable is missing on the server.",
      });
    }

    const prompt = `Analyze this university assignment and provide:
1. Clear explanation of what is required
2. Step-by-step completion plan
3. Realistic time estimate

Title: ${title}
Subject: ${subject}
Due Date: ${dueDate}
Details: ${description}

Return JSON format:
{
  "explanation": "string",
  "plan": ["step 1", "step 2", "step 3"],
  "estimatedHours": "string"
}`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: { responseMimeType: "application/json" },
    });

    const data = JSON.parse(response.text || "{}");
    return res.json({ success: true, ...data });
  } catch (error: any) {
    console.error("Error in /api/gemini/assignment:", error);
    return res.status(500).json({ success: false, error: error.message || "Failed assignment helper" });
  }
});

// 5. AI Semester Analysis
app.post("/api/gemini/semester-analysis", async (req, res) => {
  try {
    const { attendance, pendingAssignments, avgGpa, weakSubjects, studyHours } = req.body;
    const ai = getGenAI();

    if (!ai) {
      return res.status(500).json({
        success: false,
        error: "GEMINI_API_KEY environment variable is missing on the server.",
      });
    }

    const prompt = `You are a high-level academic performance analyst. Analyze this student's semester data:
- Average Attendance: ${attendance}%
- Pending Assignments: ${pendingAssignments}
- Current GPA: ${avgGpa}
- Identified Weak Subjects: ${JSON.stringify(weakSubjects)}
- Weekly Study Hours: ${studyHours}

Generate JSON with fields:
{
  "weeklyReport": "string",
  "monthlyReport": "string",
  "studyAdvice": "string",
  "motivation": "string"
}`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: { responseMimeType: "application/json" },
    });

    const data = JSON.parse(response.text || "{}");
    return res.json({ success: true, ...data });
  } catch (error: any) {
    console.error("Error in /api/gemini/semester-analysis:", error);
    return res.status(500).json({ success: false, error: error.message || "Failed semester analysis" });
  }
});

// 6. Camera Scan Notes / OCR Analysis
app.post("/api/gemini/ocr-scan", async (req, res) => {
  try {
    const { imageBase64, mimeType } = req.body;
    const ai = getGenAI();

    if (!ai) {
      return res.status(500).json({
        success: false,
        error: "GEMINI_API_KEY environment variable is missing on the server.",
      });
    }

    if (!imageBase64) {
      return res.status(400).json({ success: false, error: "No image provided." });
    }

    const base64Data = imageBase64.includes(",") ? imageBase64.split(",")[1] : imageBase64;
    const imagePart = {
      inlineData: {
        data: base64Data,
        mimeType: mimeType || "image/jpeg",
      },
    };

    const textPart = {
      text: "Perform OCR on these scanned handwritten/printed study notes or whiteboard photo. Extract all readable text accurately, summarize key takeaways, and list action items. Return JSON with keys: extractedText, summary, actionItems (array of strings)."
    };

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: { parts: [imagePart, textPart] },
      config: { responseMimeType: "application/json" }
    });

    const data = JSON.parse(response.text || "{}");
    return res.json({ success: true, ...data });
  } catch (error: any) {
    console.error("Error in /api/gemini/ocr-scan:", error);
    return res.status(500).json({ success: false, error: error.message || "Failed image OCR analysis" });
  }
});

// Serve frontend with Vite in dev mode or static files in production
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[CampusPilot] Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
